from bashbox import bashbox

single = bashbox()
single.setTheme("single")
single.setTitle("Single")
single.setText(0, "This is a bashbox with single theme.")
single.draw()
single.setColumns(2)
single.setText(0, "This is a bashbox with single theme.")
single.setText(1, "This is another column.", "And a second line.")
single.draw()

double = bashbox()
double.setTheme("double")
double.setTitle("Double")
double.setText(0, "This is a bashbox with double theme.")
double.draw()
double.setColumns(2)
double.setText(0, "This is a bashbox with double theme.")
double.setText(1, "This is another column.", "And a second line.")
double.draw()

barebone = bashbox()
barebone.setTheme("barebone")
barebone.setTitle("Barebone")
barebone.setText(0, "This is a bashbox with barebone theme.")
barebone.draw()
barebone.setColumns(2)
barebone.setText(0, "This is a bashbox with barebone theme.")
barebone.setText(1, "This is another column.", "And a second line.")
barebone.draw()

default = bashbox()
default.setTitle("Default")
default.setText(0, "This is a bashbox with default theme.")
default.draw()
default.setColumns(2)
default.setText(0, "This is a bashbox with default theme.")
default.setText(1, "This is another column.", "And a second line.")
default.draw()