name: Publish to Test PyPI

on:
  push:
    branches:
      - dev
      
jobs:
  deploy:
    name: Build & Deploy

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install wheel
    - name: Build package
      run: python -m build
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

  test:
    name: Test Package
    needs: deploy

    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install Bashbox
      run: |
        python -m pip install --upgrade pip
        pip install --index-url https://test.pypi.org/simple/ bashbox

    - name: Test Bashbox
      uses: jannekem/run-python-script-action@v1
      with: 
        script: |
          from bashbox import bashbox
          box = bashbox("test")
          box.draw()
